name: Run Playwright + Pytest Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install allure-pytest allure-commandline
          playwright install --with-deps

      - name: Run Playwright Tests
        continue-on-error: true
        run: |
          echo "⚙️ Running Playwright tests..."
          pytest tests/ -v --alluredir=allure-results || echo "⚠️ Tests failed but continuing..."

      - name: Check Allure Results
        if: always()
        run: |
          echo "📂 Listing allure-results directory:"
          ls -la allure-results || echo "❌ No allure-results found!"

      - name: Generate Allure Report
        if: always()
        run: |
          echo "🧪 Generating Allure report..."
          allure generate allure-results --clean -o allure-report || echo "⚠️ Skipping report generation due to missing results."

      - name: Upload Allure Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./allure-report
          force_orphan: true
